version: '3.8'
services:
  neo4j:
    image: neo4j:5.17.0
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_dbms_security_auth__minimum__password__length: "1"
      NEO4J_AUTH: "neo4j/admin"
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data: